### ISSUE TITLE
RuntimeError: view size is not compatible with input tensor's size and stride 

### ISSUE THREAD

**Issue by longkang1** [bboylyg/NAD#1]
Hello,

When I deploy and try to run the codes, here comes an issue:

```
----------- Train Initialization --------------
epoch: 0  lr: 0.1000
Traceback (most recent call last):
  File "main.py", line 204, in <module>
    main()
  File "main.py", line 201, in main
    train(opt)
  File "main.py", line 171, in train
    test(opt, test_clean_loader, test_bad_loader, nets,
  File "main.py", line 72, in test
    prec1, prec5 = accuracy(output_s, target, topk=(1, 5))
  File "/home/longkangli/NAD/utils/util.py", line 63, in accuracy
    correct_k = correct[:k].view(-1).float().sum(0)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

Then I change the code according to the error messages. 
In the File: "~/NAD/utils/util.py", line 63, in accuracy
change: "correct_k = correct[:k].view(-1).float().sum(0)" to "correct_k = correct[:k].contiguous().view(-1).float().sum(0)".
Then it works.

My environment: python3.8, py-torch1.7, cuda10.2.

Not sure if the problem comes from the different versions of environments. Anyway~

Regards.

**Comment by bboylyg** [comment]
Hi LongKang,
Thanks for raising the issue and provide a solution for the question!
More explanation is here [https://stackoverflow.com/questions/48915810/pytorch-contiguous]
