### ISSUE TITLE
What config did you use to have the model return the activations?

### ISSUE THREAD

**Issue by tituslhy** [bboylyg/NAD#12]
Hello, 

I'm trying to understand why your model is returning 3 activations along with the outputs when running inferences.

line 27 of main.py: activation1_s, activation2_s, activation3_s, output_s = snet(img)

Was there some thought process in returning the last 3 activations?

**Comment by bboylyg** [comment]
Hi, please see the code [here ](https://github.com/bboylyg/NAD/blob/f17b71390f61fe24335728bfea53e4fe86ee450b/models/wresnet.py#L97) to get details about returning activations.
