### ISSUE TITLE
is it possible to transfer NAD to other models?( for example resnet18)

### ISSUE THREAD

**Issue by andyclsr** [bboylyg/NAD#16]
I would like to inquire about the possibility of transferring the NAD technique to other models, specifically ResNet18. Currently, NAD is implemented with WideRes, but I am interested in exploring its applicability to different architectures.

Could you provide insights or guidance on whether it is feasible to adapt NAD to models other than the original one it was designed for? If so, are there any specific considerations or modifications that need to be taken into account? I would appreciate any information or recommendations regarding this matter.

Thank you!

**Comment by pppppkun** [comment]
> I would like to inquire about the possibility of transferring the NAD technique to other models, specifically ResNet18. Currently, NAD is implemented with WideRes, but I am interested in exploring its applicability to different architectures.
> 
> Could you provide insights or guidance on whether it is feasible to adapt NAD to models other than the original one it was designed for? If so, are there any specific considerations or modifications that need to be taken into account? I would appreciate any information or recommendations regarding this matter.
> 
> Thank you!

Hi, I also want to know how to transfer the NAD to ResNet18.  I see you closed issue, can you provide some help with that please?

**Comment by andyclsr** [comment]
> > I would like to inquire about the possibility of transferring the NAD technique to other models, specifically ResNet18. Currently, NAD is implemented with WideRes, but I am interested in exploring its applicability to different architectures.
> > Could you provide insights or guidance on whether it is feasible to adapt NAD to models other than the original one it was designed for? If so, are there any specific considerations or modifications that need to be taken into account? I would appreciate any information or recommendations regarding this matter.
> > Thank you!
> 
> Hi, I also want to know how to transfer the NAD to ResNet18. I see you closed issue, can you provide some help with that please?



this is the reply of the author, hope it may help you well.

> You could easily transfer the NAD from original WideResNet to the other model architectures like ResNet by only changing the config[https://github.com/bboylyg/NAD/blob/f17b71390f61fe24335728bfea53e4fe86ee450b/config.py#L38] of model name to ResNet-34. For details, please carefully review the code[https://github.com/bboylyg/NAD/blob/f17b71390f61fe24335728bfea53e4fe86ee450b/models/resnet.py#L165] which will tell you how to extract the activation maps from each of output layers on different model architectures.

**Comment by pppppkun** [comment]
> > > I would like to inquire about the possibility of transferring the NAD technique to other models, specifically ResNet18. Currently, NAD is implemented with WideRes, but I am interested in exploring its applicability to different architectures.
> > > Could you provide insights or guidance on whether it is feasible to adapt NAD to models other than the original one it was designed for? If so, are there any specific considerations or modifications that need to be taken into account? I would appreciate any information or recommendations regarding this matter.
> > > Thank you!
> > 
> > 
> > Hi, I also want to know how to transfer the NAD to ResNet18. I see you closed issue, can you provide some help with that please?
> 
> this is the reply of the author, hope it may help you well.
> 
> > You could easily transfer the NAD from original WideResNet to the other model architectures like ResNet by only changing the config[https://github.com/bboylyg/NAD/blob/f17b71390f61fe24335728bfea53e4fe86ee450b/config.py#L38] of model name to ResNet-34. For details, please carefully review the code[https://github.com/bboylyg/NAD/blob/f17b71390f61fe24335728bfea53e4fe86ee450b/models/resnet.py#L165] which will tell you how to extract the activation maps from each of output layers on different model architectures.

Thanks!
