### ISSUE TITLE
How to train CL and Refool backdoored model?

### ISSUE THREAD

**Issue by Urdarbrunner** [bboylyg/NAD#5]
Hello, 
I'm very interested in this paper, and I try to reproduce the work.
When I tried to train the backdoored model on CIFAR-10, I followed the advice in `readme.md` and successfully trained the `BadNets`, `Trojan`, `Blend` and `SIG` backdoored models mentioned in the paper . 
However, when I tried to train the `Clean-label` and `Refool` backdoored models, I found that it seemed impossible to do this by simply modifying parameters in `configs.py`. Then I went to the `CL` and `Refool` links mentioned in `readme.md`, but I still didn't know how to implement these two backdoor attacks.
Now, I have absolutely no idea how to train these two backdoored models, if you could give me some advice and help I would be very grateful

**Comment by bboylyg** [comment]
Hi, Thank you for your attention to our work. The code of CL attack is shown in this link (https://github.com/hkunzhe/label_consistent_attacks_pytorch). The official code of Refool is shown here (https://github.com/DreamtaleCore/Refool). Hope this answer is helpful to you!
