### ISSUE TITLE
performance on GTSRB

### ISSUE THREAD

**Issue by bingxumu** [bboylyg/NAD#7]
Hi! Thanks for your great work!

Have you tested the defense effect of NAD against attacks other than refool on gtsrb ?  such as badnets, blend, sig,
If so, could you share the experimental results. 
I'd appreciate it very much!

best!

**Comment by bboylyg** [comment]
Sorry for the late reply. if you want to reproduce the attacks on GTSRB, you can easy to replace the training data of CIFAR-10 by the GTSRB dataset to reproduce these backdoor attacks. GTSRB dataset can be downloaded at this [link] (https://sid.erda.dk/public/archives/daaeac0d7ce1152aea9b61d9f1e19370/). The other settings of attacks may be similar to the CIFAR-10's.
