### ISSUE TITLE
How does the attention loss work

### ISSUE THREAD

**Issue by zeabin** [bboylyg/NAD#8]
Hi, thanks for sharing the code.

I notice that `detach()` is called before `backward()` for attention loss in `train_step` and the back propagation should not go through attention loss. So how can the attention loss work? 
https://github.com/bboylyg/NAD/blob/d61e4d74ee697f125336bfc42a03c707679071a6/main.py#L30-L34

**Comment by bboylyg** [comment]
Hi, thank you very much for your reminder. This error has been fixed now.
